name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - develop  # 监听 develop 分支的 push 事件
  workflow_dispatch:  # 手动触发

# 确保赋予写入权限
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set environment variables
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build VitePress site
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 如果仍然遇到权限问题，考虑将下行替换为使用 PAT:
          # github_token: ${{ secrets.ACCESS_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages
